### ISSUE TITLE
How to use IPython-notebook-extensions

### ISSUE THREAD

**Issue by AtsushiSakai** [pl31/heroku-jupyter#1]
Hi.

Your heroku-jupyter is great!!. I love it.

However, I would like to use IPython-notebook-extensions on the heroku-jupyter.
[ipython-contrib/IPython-notebook-extensions: Some extensions for Jupyter notebook](https://github.com/ipython-contrib/IPython-notebook-extensions)

I think it makes heroku-jupyter better.
So, could you please add description about how to use IPython-notebook-extensions in README.md?

Thanks you.
Atsushi

**Comment by pl31** [comment]
Hi Atsushi,

sorry for late response and thanks for your feedback.

The notebook extensions look really great and I was able to test them locally. But I was not able to install the extension successfully inside heroku-jupyter.

I tried:
- adding `git+git://github.com/ipython-contrib/IPython-notebook-extensions.git` to pip section in `environment.yml`
- adding `pip install git+git://github.com/ipython-contrib/IPython-notebook-extensions.git` to `start_jupyter`
- adding `conda install -c jochym nbextensions=master` to `start_jupyter`

Do you have an idea to get these installed?

Cheers,
Patrick

**Comment by AtsushiSakai** [comment]
It' great!! Thanks you.
