### ISSUE TITLE
Easy Deploy to heroku not working

### ISSUE THREAD

**Issue by ghost** [pl31/heroku-jupyter#10]
Hi,

I've been trying to deploy to heroku using the heroku button.
Unfortunately, Heroku seems to get stuck configuring the environment.

**Comment by pl31** [comment]
Same behaviour for me.

The error log shows:
```
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed
```

Installing manually or explicitely defining the buildpack in the app settings works like expected. So it seems heroku ignores the buildpack settings in `app.json`. Regarding the docs https://devcenter.heroku.com/articles/app-json-schema it should work....

I need some more time to investigate.

**Comment by ghost** [comment]
Awesome, Thanks, I'll try manually.

**Comment by pl31** [comment]
Hello ametzler33,

heroku-support helped me to fix the app.json. It is now working for me, again.

Could you try as well?

Cheers,
Patrick

**Comment by ghost** [comment]
Thanks, just gave it another try.
The deploy button now redirects me to create a new app in heroku, which I then have to manually link with github.

Brgds,
Antek

**Comment by pl31** [comment]
Do you have any browser plugins like ghostery or adblock running? What browser do you use?

I just tried again, and it worked.... weird :(.

Regards
Patrick

**Comment by ghost** [comment]
I was using safari with Adblock disabled. I've now tried from a different device  and everything worked properly, so I guess the problem was with my laptop.

Antek
