### ISSUE TITLE
No way to install other python packages without forking?

### ISSUE THREAD

**Issue by cauebs** [pl31/heroku-jupyter#12]

**Comment by pl31** [comment]
Hello cauebs,

I do not like the forking as well, but I don't have any other idea. Package definition is an individual task, so you need an individual location where to store your environment configuration.

**Comment by cauebs** [comment]
For now I'm using this workaround. I can't decide whether I find it cute or just terribly ugly. But it works 😛 

```python
def include(package, alias=None):
    try:
        module = __import__(package)
    except ImportError as e:
        import pip
        pip.main(['install', e.name])
        module = __import__(e.name)
    globals()[alias or package] = module
    
include('numpy', 'np')
include('pandas', 'pd')
```

**Comment by pl31** [comment]
Your workaround should be fine. Just two sidenotes:

- heroku-jupyter is installed using anconda. If I use anaconda, I prefer using conda as primary package manager. I only use pip, if I can't install a package with conda. But that's just my preference.
- Installing packages dynamically will download the packages after each restart of the container, as it is not included during the buildpack run.

**Comment by BrandenKeck** [comment]
Hi All,
Sorry, but I am relatively knew to using python in this way.  If I wanted to do the same, would the code above be added to the jupyter_notebook_config.py file?  And would simply adding the function to the end of the file and adding the function calls to the main try statement suffice?

Thank you for your help
Branden

**Comment by pl31** [comment]
The code can be used directly inside a notebook and should go to the top of the notebook.
