### ISSUE TITLE
Notebook List Empty

### ISSUE THREAD

**Issue by antmarakis** [pl31/heroku-jupyter#18]
Hello. I am interested in using this for a project I work for.

I forked the repository and entered some notebooks in the `notebooks` folder. Unfortunately, when I hit the deploy button, they don't show up. Instead I get a message reading 'Notebook List Empty' in the Jupyter home page.

Am I misunderstanding what this is?

**Comment by pl31** [comment]
Hi MrDupin,

as long as #14 is open there will be trouble conserving notebooks.

If you want to use the notebook directory, you need to disable pgcontents (saving notebooks to the postgres database). Then your notebooks will show up. Be aware, that your changes to those notebooks are lost, if you restart your dynos.

Cheers
Patrick

**Comment by antmarakis** [comment]
OK, thanks for the help.
