### ISSUE TITLE
Saving files (directory not in tree)

### ISSUE THREAD

**Issue by gmaijoe** [pl31/heroku-jupyter#20]
I'm saving a file on jupyter (deployed on heroku).

I cannot see the saved file in the local working tree.

However, the program is able to read the file.

This is odd. I'd like to be able to see the files I save and download them locally.

Any help is appreciated.

**Comment by pl31** [comment]
Depends on quantopian/pgcontents#28. You could try using Python 2.

**Comment by pl31** [comment]
@gmaijoe Today I retried the standard configuration and saving works fine now.

Can you check if you problem does still exist?

**Comment by pl31** [comment]
Closed. Seem to be no issue.

**Comment by pl31** [comment]
Closed. Seem to be no issue.
