### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by ph0rque** [pl31/heroku-jupyter#24]
Whenever I upload a notebook, as soon as it starts running, it encounters connection issues:

![jupyter_notebook_connection](https://user-images.githubusercontent.com/1257/37676689-f774f534-2c4e-11e8-9f32-a73af1e420f4.gif)

I cannot reproduce the issue when running locally (using `heroku local`). On Heroku, this problem repeats and does not allow the execution of any code. Any hints as to what may be causing the issue?

**Comment by ph0rque** [comment]
Here's the heroku log:

```
[I 18:52:48.902 NotebookApp] Adapting to protocol v5.1 for kernel ac549
[E 18:52:48.903 NotebookApp] Uncaught exception in /api/kernels/ac549/channels
    Traceback (most recent call last):
      File "/app/.conda/lib/python3.6/site-packages/tornado/websocket.py", line 498, in _run_callback
        result = callback(*args, **kwargs)
      File "/app/.conda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 260, in open
        super(ZMQChannelsHandler, self).open()
      File "/app/.conda/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 176, in open
         self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

**Comment by pl31** [comment]
Hi, I thought I fixed this today a few hours ago.

If you find tornado 5 installed in your buildlog, please try to reinstall. tornado should be installed in version 4.x.x then.

Should have been this commit: 3ab8e2d

**Comment by pl31** [comment]
btw: nice gif

**Comment by ph0rque** [comment]
Thanks for the quick response! Will try that next and report back.

**Comment by ph0rque** [comment]
OK, I was able to solve the issue by copying ` - tornado = 4.5` from `environments/default.yml` to `environment.yml`. I am not a pythonista, so I'm not sure if it's an issue with the `environment.yml` file overriding `environments/default.yml`, or something else?

**Comment by pl31** [comment]
Thanks for feedback - I forgot to update the one in the root folder.
Added the change as well.
