### ISSUE TITLE
Redirect to https on Heroku?

### ISSUE THREAD

**Issue by ph0rque** [pl31/heroku-jupyter#25]
Is it possible to automatically redirect to the same URL but with `https` without modifying any of the supporting packages?

**Comment by pl31** [comment]
You want to force http traffic to https? Googling did not give me any useful pages. Added some links as "bookmark".

For heroku I found this here:
https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls

Rather old:
https://github.com/ipython/ipython/issues/1460/

**Comment by ph0rque** [comment]
Thanks! From the heroku link, it seems this has to be done at an app level:

> Django
> Set SECURE_SSL_REDIRECT to True.
>
> Flask
> You can use https://github.com/kennethreitz/flask-sslify to handle this for you.

I also saw the other link.

It seems that since jupyter runs tornado, there should be a way to add some kind of setting or wrapper to this code to enable this functionality: https://github.com/tornadoweb/tornado/issues/523
