### ISSUE TITLE
Size problem trying to use the numpy module

### ISSUE THREAD

**Issue by giovixo** [pl31/heroku-jupyter#26]
Unfortunately,
using heroku service, the scientific python modules are too large for deployment.

In the following "failed build" I tried to include numpy in environment.yml: 

-----> Compressing...
 !     Compiled slug size: 678.3M is too large (max is 500M).
 !     See: http://devcenter.heroku.com/articles/slug-size
 !     Push failed

**Comment by pl31** [comment]
Do you have a proposal on how to improve the situation?
https://devcenter.heroku.com/articles/slug-compiler#slug-size

**Comment by giovixo** [comment]
I do not have a simple solution. In general, a python data science environment requires a lot of memory in term of loaded modules (numpy, matplotlib, etc..). In a quite ideal case, all this stuff should be in a common place (the buildpack?), not within the application. Is it possible in principle?
