### ISSUE TITLE
Adding JavaScript support

### ISSUE THREAD

**Issue by cs775-unh** [pl31/heroku-jupyter#28]
How would I extend your app to include javascript (ijavascript) support? I would like the notebooks to include both python and javascript language support.

Thanks in advance

**Comment by pl31** [comment]
The squence to install ijavascript seems to be like this here:
 
```
conda install nodejs
npm install -g ijavascript
ijsinstall
```
Adding `nodejs` to environment.yml is easy, but the two other commands are a little bit more tricky. I think we might need a postbuild command in the conda-buildpack and parametrize via environment variables.

**Comment by pl31** [comment]
Just found this here:
https://devcenter.heroku.com/changelog-items/1332

Using heroku.yml looks like an alternative.
