### ISSUE TITLE
Issues while deploying on heroku

### ISSUE THREAD

**Issue by haseebehsan** [pl31/heroku-jupyter#38]
Hi, I was using the click to deploy button below and it gave this error

```
-----> Installing Dependencies using /tmp/build_56938d30a27dd84cca915e0c8f940181/environments/default.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
ResolvePackageNotFound: 
  - notebook=4
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by jefflarkin** [comment]
Same for me.

**Comment by haseebehsan** [comment]
I Fixed this btw by specifying the version of notebook==5 but ran into different problems of pgcontents or something later after installation when trying to run the jupyter

> Same for me.

**Comment by jefflarkin** [comment]
@haseebehsan Thanks, I actually found your fork last night. I had to change the IP to `0.0.0.0` and then had a successful deploy, but am also hitting issues with pgcontents that I still need to dig into. I'll keep a eye on your fork. Thanks.

**Comment by haseebehsan** [comment]
I might not work on it this week but if you find any solution, do let me know too, I really need to install this.

> @haseebehsan Thanks, I actually found your fork last night. I had to change the IP to `0.0.0.0` and then had a successful deploy, but am also hitting issues with pgcontents that I still need to dig into. I'll keep a eye on your fork. Thanks.

**Comment by pl31** [comment]
I tried adding an alternative environment (environments/latest.yml) without any version binding. Find Deploy button in the table at the end of README.md.

Still initial setup of the database fails
`psycopg2.errors.UndefinedObject: constraint "directories_parent_user_id_fkey" of relation "directories" does not exist`

This might be a pgcontents bug: https://github.com/quantopian/pgcontents/issues/74

**Comment by pl31** [comment]
I do not find a valid environment.yml

- pgcontents 0.6.0 will not initialized properly
- pgcontents 0.5.3 needs notebook = 4 (IPython = 5), which is not available anymore

**Comment by jefflarkin** [comment]
@pl31 @haseebehsan yes, this is how far I got as well. Thanks for looking at it. If I find a solution, I'll post it here. I agree, it appears to be a pgcontents 0.6.0 bug that prevents initialization. I'm tempted to sift through the code to find the initialization SQL query and then initialize the db manually to see if this fixes it.

**Comment by willsmith-delete** [comment]
Any updates? Im having the same issue

**Comment by haseebehsan** [comment]
@pl31 any leads, yet?

**Comment by pl31** [comment]
I tried to deploy "latest.yml". Installation works fine, starting results in an error:

```
2020-10-15T17:16:25.617615+00:00 app[web.1]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "pgcontents.users" does not exist
2020-10-15T17:16:25.617616+00:00 app[web.1]: LINE 1: INSERT INTO pgcontents.users (id) VALUES ('heroku')
```

There is a similar case here: https://github.com/quantopian/pgcontents/issues/75

So, no stable and running configuration, yet.
