### ISSUE TITLE
How to use Python v2?

### ISSUE THREAD

**Issue by onlineth** [pl31/heroku-jupyter#6]
Hello, how can I add Python v2.x to the Jupiter Notebook Heroku Instance? I've tried adding a `conda_runtime.txt` file with the contents reading, `Miniconda2-latest-Linux-x86_64.sh` but it still seems to use Python v3.

**Comment by pl31** [comment]
I tried and can confirm your observation. The buildpack seems to update the python version in one of the update steps.

Fixing the python version in environment.yml seems to be working:

```
name: ipython-notebook
dependencies:
  - python=2.7
  - ...
```

Find an example in the python2.7 branch:
[https://github.com/pl31/heroku-jupyter/tree/python2.7](https://github.com/pl31/heroku-jupyter/tree/python2.7)

The use of `conda_runtime` is optional, but using `Miniconda-latest-Linux-x86_64.sh` could speedup the build job, as the python version will not be changed from 3.5 to 2.7.

**Comment by pl31** [comment]
I added a small description in the Readme.

@onlineth Does it work for you like this?

**Comment by onlineth** [comment]
Works great, thank you @pl31 :)
